### ISSUE TITLE
Question: Is there a license for this repo?/Will there be a license for this repo?

### ISSUE THREAD

**Issue by Shuenhoy** [MrZ626/Techmino#23]
Hi,

I didn't see a license in this repo. Is this a _proprietary software with source codes provided_, which means the others should only browse the codes but should not use or distribute it? This may also affect those who want to contribute via PRs.

(Reference: https://choosealicense.com/no-permission/)

Thanks

**Comment by MrZ626** [comment]
I don't know much about license, there will be a license later.
